name: Update Logo Daily

on:
  schedule:
    - cron: '0 16 * * 1-5'  # 5PM UK time (16:00 UTC)
  workflow_dispatch:
  
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python update-logo.py

      - name: Commit and push changes
        run: |
          git config user.name "Sahin AutoBot"
          git config user.email "auto@macroscopelondon.com"
          git add logo.png
          git commit -m "Auto-update logo based on market close" || echo "No changes"
          git push
